name: Version Update

on:
  push:
    tags:
      - v*

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Update version in files
        run: |
          # Check if files exist
          if [ ! -f "setup.py" ]; then
            echo "Error: setup.py not found"
            exit 1
          fi
          if [ ! -f "fewlearn/__init__.py" ]; then
            echo "Error: fewlearn/__init__.py not found"
            exit 1
          fi
          
          # Update version numbers
          sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" setup.py
          sed -i "s/__version__ = \"[^\"]*\"/__version__ = \"$VERSION\"/" fewlearn/__init__.py
          
          # Verify updates
          echo "Updated versions to $VERSION"
          echo "setup.py version:"
          grep "version=\"" setup.py
          echo "init.py version:"
          grep "__version__" fewlearn/__init__.py
      
      - name: Commit version updates
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add setup.py fewlearn/__init__.py
          git commit -m "chore: update version to $VERSION"
          git push origin HEAD:main 